### ISSUE TITLE
3d model of the top doesn't match the photo

### ISSUE THREAD

**Issue by beanz** [michd/esp32-wled-level-shifter#1]
The photo appears to show the top having cutouts to permit it to sit flush to the lip on the bottom **and** allow the mount "wings" of the bottom part to stick out. However, the 3d model of the top has no such cutouts.

**Comment by michd** [comment]
Thanks Mark! I've now included the changes I forgot to commit, updated the screenshot in the README, and created a new release with updated exported STLs. -> [enclosure-rev2](https://github.com/michd/esp32-wled-level-shifter/releases/tag/enclosure-rev2)

Fixed by 4d2196c90ba8f40cf075ebc1ce1ca5c4d67360cb.
